### ISSUE TITLE
module file was created by an older version of the compiler

### ISSUE THREAD

**Issue by masbenx** [sinch/ios-swift-verification#1]
when i run on xcode 7 using swift 2.0 i got error
```
module file was created by an older version of the compiler; rebuild SinchVerivication and try Again
```

**Comment by cahlbin** [comment]
We are working on supporting Swift 2.0 and a new version of the Sinch Verification SDK will be available soon (estimate is end of this week).

**Comment by fmendoza** [comment]
Any news on support for swift 2.0? We are about to launch our app for IOS, but cannot without SMS verification.

**Comment by cahlbin** [comment]
Can you try with the following __beta__ release package and let me know how how it works out for you ?
https://download.sinch.com/verification/ios/beta/SinchVerification-iOS-1.2-8067eae.tar.bz2

FYI: That package also contains support for LLVM Bitcode.

**Comment by fmendoza** [comment]
Thanks, but i try to run the project and it seems that still use the old sintax for swift 2.0 and get the same message "module file was created by an older version..." : (

**Comment by cahlbin** [comment]
@fmendoza I haven't updated this tutorial project yet to Swift 2.0 yet. We will do that (You can probably run the Xcode 7 "wizard" to migrate the project to Swift 2.0). Regarding the error "module file was created by an older version...", did you download the framework from the link in the previous comment and dropped that into the tutorial project on your local dev machine?

**Comment by fmendoza** [comment]
Yes, i did that with no luck

**Comment by fmendoza** [comment]
Now i got "no such module" alert message in "import SinchVerfication;"

**Comment by francoist** [comment]
A new iOS SDK with support for Swift 2.0 and LLVM Bitcode is now available here: http://www.sinch.com/ios-verification-sdk or via CocoaPod (http://cocoapods.org/pods/SinchVerification-Swift ). The tutorial will also be updated shortly.

**Comment by fmendoza** [comment]
it works :)

**Comment by masbenx** [comment]
thanks.. it works on me..

**Comment by masbenx** [comment]
on swift 2.1, the error showing again.
can you update the cocoapod build? 
thanks

**Comment by cahlbin** [comment]
@masbenx Have you tried version 1.3.3? It should be available also as cocoapod.

**Comment by masbenx** [comment]
i tried to update cocoapod depedencies, but it show that my project Using SinchVerification-Swift (1.2) not version 1.3.3

**Comment by cahlbin** [comment]
@masbenx How does your Podfile look? Cause the 1.3.3 is published, https://cocoapods.org/?q=sinch and https://github.com/CocoaPods/Specs/blob/master/Specs/SinchVerification-Swift/1.3.3/SinchVerification-Swift.podspec.json

**Comment by masbenx** [comment]
thanks it works on me..
I try to add the version1.3.3 to podfile and update the pod.

**Comment by jaimefili** [comment]
Updated to Xcode 7.3 and now I'm getting this error. Anyone knows how to fix this?
Thanks.
(installed sinch via cocoapods)

**Comment by khanamir** [comment]
On swift 2.2 the error is showing again. Could you please update the build?

**Comment by nishp1** [comment]
I am seeing the error with version 2.2 as well.

**Comment by kyco16** [comment]
Jumping on into swift 3 and this error still exists. I'd hate to not use this great service

**Comment by astanton** [comment]
I'm running into this issue when trying to use Swift 2.3 and I just updated to the latest cocoapod 1.4.6.

Any suggestions for this?  Really want to get our app building in Xcode 8 asap, thanks.

**Comment by ArniDexian** [comment]
up, swift 2.3 isn't supported

**Comment by astanton** [comment]
What is the recommended way to use the Sinch API for a Swift project on Xcode 8?

**Comment by zffx** [comment]
The latest version of iOS Verification SDK (1.4.7) has been released. It is compatible with Xcode8 and all Swift versions, please update to the latest.

**Comment by astanton** [comment]
Ah okay cool thanks, I will give that one a go.

**Comment by zffx** [comment]
More info about Swift compatibility:
The binary SinchVerification.framework for swift (i.e. the pod SinchVerification-Swift) in 1.4.7 is using Swift 2.3.  
If you require Swift 3 source compatibility, you will need to use the source bindings that are in the swift3/ folder in the package.

**Comment by DallasHoelscher** [comment]
When doing another pod install, its still downloading version 1.4.4, How do i make it install v 1.4.7? Is there better instructions on getting the correct sinch installed for swift 3?

**Comment by zffx** [comment]
Do you have a Podfile.lock file for SinchVerification in your directory that locks the SDK version to 1.4.4? Could you try "pod **update** SinchVerification-Swift" instead?
Regarding better instructions for Swift 3, let me consult my colleagues and get back to you.

**Comment by zffx** [comment]
@DallasHoelscher Our Swift binary framework will support swift 3 in the next release. At this moment, the Swift binary framework will still only work under swift 2.3. 

If you need the SDK to work with Swift 3, you need to take the obj-c version of the binary framework together with the swift source bindings in the swift3/ directory. Unfortunately we don't have more detailed instructions for that other than the ones already in your download package.

**Comment by DallasHoelscher** [comment]
@zffx Thank you for your help. I will look into following the documentation. Any ideas on when the next release will be?

**Comment by zffx** [comment]
@DallasHoelscher the next release should come soon, possibly in a few days.

**Comment by zffx** [comment]
@DallasHoelscher FYI, the Swift3 binary frame will be released today or latest tomorrow.
